### ISSUE TITLE
Searching for "whale" returns first result in Ch. 32

### ISSUE THREAD

**Issue by dwhly** [futurepress/epubjs-angular-reader#25]
http://epubjs-reader.appspot.com/

Using new search feature on Moby Dick.
Type "whale".
First result returns from ch. 32 "Cetology".
But whale is used throughout.  :)

D

**Comment by fchasen** [comment]
Great catch. Scrolling down it looks like results from the entire book are returned, but they are unordered.

@AJRenold - We need to update the results order to match position in epub spine.

**Comment by dwhly** [comment]
ah… good.  scrolled down a bit but clearly not enough!

**Comment by AJRenold** [comment]
Search results are now sorted by chapter https://github.com/futurepress/epubjs-search/commit/995e824d94a58127a72d682438682dc738e332d9
